@val external repoName: string = "repoName"
@val external repoVersion: string = "repoVersion"
@val external repoPublicPath: string = "publicPath"
@val external backendEndPoint: string = "backendEndPoint"
@val external confirmEndPoint: string = "confirmEndPoint"
@val external sdkUrl: string = "sdkUrl"
@val external logEndpoint: string = "logEndpoint"
@val external sentryDSN: string = "sentryDSN"
@val external sentryScriptUrl: string = "sentryScriptUrl"
@val external enableLogging: bool = "enableLogging"
@val external loggingLevelStr: string = "loggingLevel"
@val external maxLogsPushedPerEventName: int = "maxLogsPushedPerEventName"
let targetOrigin: string = "*"
@val external isInteg: bool = "isIntegrationEnv"
@val external isSandbox: bool = "isSandboxEnv"
@val external isProd: bool = "isProductionEnv"
@val external isLocal: bool = "isLocal"
// Microblink BlinkCard license key (FQDN-locked to the hs-web origin), baked at
// build time. Empty string => the "Scan card" button is not rendered.
@val external microblinkLicenseKey: string = "microblink_license_key"
// Card-scan OCR engine selector, baked at build time: "tesseract" | "microblink"
// | "" (off). Empty string => the "Scan card" button is not rendered.
@val external cardScanEngine: string = "card_scan_engine"
